Repository CloneCodeMates/MarketKurly, pull requests merged in 2025-03, with the labels that each got.

#48 feat: Event JS 완료
  src/assets/images/event/event-banner1.png
  src/assets/images/event/event-banner10.jpg
  src/assets/images/event/event-banner2.png
  src/assets/images/event/event-banner3.png
  src/assets/images/event/event-banner4.jpg
  src/assets/images/event/event-banner5.png
  src/assets/images/event/event-banner6.jpg
  src/assets/images/event/event-banner7.png
  src/assets/images/event/event-banner8.jpg
  src/assets/images/event/event-banner9.jpg
  src/assets/images/event1.jpg
  src/css/sections/event.css
  src/js/include/event.js
  src/js/main.js
  src/pages/includes/event.html
Labels: ✨feat

#55 feat: 모달 닫을 때 수량 및 합계 초기화
  src/js/include/modal.js
Labels: ✨feat

#56 refactor: 코드 개선(불필요한 코드 제거)
  src/index.html
  src/pages/includes/banner.html
  src/pages/includes/event.html
  src/pages/includes/footer.html
  src/pages/includes/header.html
  src/pages/includes/nav.html
  src/pages/includes/rank.html
  src/pages/includes/sidebar.html
  src/pages/includes/time.html
  src/pages/includes/top-banner.html
Labels: ♻️refactor

#58 feat: Nav JS 완료
  src/assets/icons/nav/search-icon_fixed.svg
  src/css/sections/nav.css
  src/js/include/nav.js
  src/js/main.js
  src/pages/includes/nav.html
Labels: ✨feat

#60 feat: Time JS 완료
  src/assets/images/sale-product1.jpg
  src/assets/images/time/time-sale-product1.jpg
  src/assets/images/time/time-sale-product2.png
  src/assets/images/time/time-sale-product3.jpeg
  src/css/sections/time.css
  src/js/include/time.js
  src/js/main.js
  src/pages/includes/time.html
Labels: ✨feat

#61 feat: Rank JS 완료
  src/assets/images/rank/rank-product1.jpg
  src/assets/images/rank/rank-product2.jpeg
  src/assets/images/rank/rank-product3.jpeg
  src/assets/images/rank/rank-product4.jpg
  src/assets/images/rank/rank-product5.jpg
  src/css/sections/rank.css
  src/js/include/modal.js
  src/js/include/rank.js
  src/js/main.js
  src/pages/includes/goods.html
  src/pages/includes/rank.html
  src/pages/includes/time.html
Labels: ✨feat

#64 fix: event.js의 event-page-index 오류 해결
  src/js/include/event.js
Labels: 🐛fixBug

#66 feat: favicon 설정 및 title 수정 완료
  src/index.html
Labels: ✨feat, 🎨 style

#68 refactor: 절대경로로 경로 변경 완료
  src/css/sections/nav.css
  src/css/style.css
  src/index.html
  src/js/main.js
Labels: ♻️refactor

#70 Update README.md
  README.md
Labels: 📑docs

#72 refactor: Swiper 슬라이드 너비 자동 설정 방지 완료
  src/css/sections/goods.css
  src/css/sections/rank.css
  src/js/include/goods.js
  src/js/include/rank.js
Labels: ♻️refactor

#74 fix: 모든 JS 파일에 DOMContentLoaded 이벤트 리스너 추가 완료
  src/js/include/event.js
  src/js/include/header.js
  src/js/include/modal.js
  src/js/include/nav.js
  src/js/include/time.js
  src/js/include/top-banner.js
Labels: 🐛fixBug

#77 test: 각 섹션 별 코드 index.html에 병합
  index.html
  src/js/include/event.js
  src/js/include/goods.js
  src/js/include/header.js
  src/js/include/modal.js
  src/js/include/nav.js
  src/js/include/rank.js
  src/js/include/sidebar.js
  src/js/include/time.js
  src/js/include/top-banner.js
Labels: ♻️refactor, ✅test
