Repository CloneCodeMates/MarketKurly, pull requests merged in 2025-02, with the labels that each got.

#5 setting: 빈 디렉토리에 .gitignore 파일 추가
  src/assets/icons/.gitignore
  src/assets/images/.gitignore
  src/pages/includes/.gitignore
Labels: ⚙️setting

#9 feat: base.css에 공통 설정 추가 (body, a, ul 태그)
  src/css/common/base.css
Labels: ✨feat

#10 feat: Pretendard 글꼴 적용
  src/css/common/base.css
  src/css/common/font.css
  src/index.html
Labels: ✨feat

#11 feat: base.css에 공통 설정 추가 (p, button 태그)
  src/css/common/base.css
  src/index.html
Labels: ✨feat

#12 feat: Footer HTML/CSS 완료
  src/assets/icons/divider-vertical.svg
  src/assets/icons/icon_blog.png
  src/assets/icons/icon_facebook.png
  src/assets/icons/icon_instagram.png
  src/assets/icons/icon_naverpost.png
  src/assets/icons/icon_youtube.png
  src/assets/icons/logo_eprivacy.png
  src/assets/icons/logo_isms.png
  src/assets/icons/logo_isms.svg
  src/assets/icons/logo_tosspayments.svg
  src/assets/icons/logo_wooriBank.svg
  src/css/sections/footer.css
  src/css/style.css
  src/pages/includes/footer.html
Labels: ✨feat

#14 feat: body에 scroll 설정
  src/css/common/base.css
Labels: ✨feat

#15 feat: Header HTML/CSS 완료
  src/assets/icons/close-icon.svg
  src/assets/icons/header/cart-icon.svg
  src/assets/icons/header/delete-icon.svg
  src/assets/icons/header/delivery-location-icon.svg
  src/assets/icons/header/heart-favorites-icon.svg
  src/assets/icons/header/market-kurly-logo.svg
  src/assets/icons/header/search-icon.svg
  src/assets/images/support-down-arrow.png
  src/css/sections/header.css
  src/css/sections/top-banner.css
  src/css/style.css
  src/index.html
  src/pages/includes/header.html
  src/pages/includes/top-banner.html
Labels: ✨feat

#17 feat: index.html과 base.css에 공통 설정 추가(IE 호환성, border-box)
  src/css/common/base.css
  src/index.html
Labels: ✨feat

#18 feat: Event HTML/CSS 완료
  src/assets/icons/event/event-arrow.svg
  src/assets/images/event1.jpg
  src/css/sections/event.css
  src/css/style.css
  src/pages/includes/event.html
Labels: ✨feat

#22 feat: Goods HTML/CSS 완료
  src/assets/icons/goods/cart-icon.svg
  src/assets/icons/goods/goods-more-btn.svg
  src/assets/icons/goods/review-icon.svg
  src/assets/icons/goods/swiper-btn-h.svg
  src/assets/icons/goods/swiper-btn.svg
  src/assets/images/product-img1.jpeg
  src/css/sections/goods.css
  src/pages/includes/goods.html
Labels: ✨feat

#24 feat: banner HTML/CSS 완료
  src/assets/images/banner.jpg
  src/css/sections/banner.css
  src/css/style.css
  src/pages/includes/banner.html
Labels: ✨feat

#26 feat: Time HTML/CSS 완료
  src/assets/icons/time/cart-icon.svg
  src/assets/icons/time/clock-icon.svg
  src/assets/icons/time/review-icon.svg
  src/assets/images/sale-product1.jpg
  src/css/sections/time.css
  src/css/style.css
  src/pages/includes/time.html
Labels: ✨feat

#28 feat: Rank HTML/CSS 완료
  src/assets/icons/rank/view-all-arrow.svg
  src/assets/images/rank-product1.jpg
  src/assets/images/rank-product2.jpeg
  src/css/sections/rank.css
  src/css/style.css
  src/pages/includes/rank.html
Labels: ✨feat

#29 feat: Sidebar HTML/CSS 완료
  src/assets/images/sidebar-banner.jpg
  src/css/sections/sidebar.css
  src/css/style.css
  src/pages/includes/sidebar.html
Labels: ✨feat

#31 feat: 분리된 HTML 파일을 index.html에 포함 #30
  src/index.html
Labels: ✨feat

#34 refactor: HTML/CSS 수정 및 통합 (Header, Event, Time, Rank)
  src/assets/icons/cart-icon.svg
  src/assets/icons/header/cart-icon-h.svg
  src/assets/icons/header/delivery-location-icon-h.svg
  src/assets/icons/header/heart-favorites-icon-h.svg
  src/assets/icons/review-icon.svg
  src/assets/icons/swiper-btn-h.svg
  src/assets/icons/swiper-btn.svg
  src/assets/icons/time/cart-icon.svg
  src/assets/icons/time/review-icon.svg
  src/css/sections/event.css
  src/css/sections/header.css
  src/css/sections/rank.css
  src/css/sections/time.css
  src/pages/includes/header.html
  src/pages/includes/rank.html
  src/pages/includes/time.html
Labels: ♻️refactor

#35 refactor: HTML/CSS 수정 및 통합 (Footer, Nav, Goods, Sidebar, banner)
  src/assets/icons/footer/divider-vertical.svg
  src/assets/icons/footer/icon_blog.png
  src/assets/icons/footer/icon_facebook.png
  src/assets/icons/footer/icon_instagram.png
  src/assets/icons/footer/icon_naverpost.png
  src/assets/icons/footer/icon_youtube.png
  src/assets/icons/footer/logo_eprivacy.png
  src/assets/icons/footer/logo_isms.svg
  src/assets/icons/footer/logo_tosspayments.svg
  src/assets/icons/footer/logo_wooriBank.svg
  src/assets/icons/logo_isms.png
  src/css/sections/footer.css
  src/css/sections/goods.css
  src/css/sections/header.css
  src/css/sections/nav.css
  src/css/sections/sidebar.css
  src/css/style.css
  src/pages/includes/footer.html
  src/pages/includes/goods.html
Labels: ♻️refactor

#36 style: base.css에 공통 설정 추가 (body, button, h1~h5)
  src/css/common/base.css
  src/css/sections/time.css
Labels: 🎨 style

#37 style: Footer HTML/CSS 수정
  src/css/sections/footer.css
  src/pages/includes/footer.html
Labels: 🎨 style

#42 feat: sidebar JS 수정
  src/css/sections/sidebar.css
  src/index.html
  src/js/include/sidebar.js
  src/pages/includes/sidebar.html
Labels: ✨feat

#44 feat: Header JS 완료
  src/css/sections/header.css
  src/css/sections/top-banner.css
  src/index.html
  src/js/include/header.js
  src/js/include/top-banner.js
  src/js/main.js
  src/pages/includes/header.html
  src/pages/includes/top-banner.html
Labels: ✨feat

#45 feat: Header HTML/CSS 추가
  src/assets/icons/header/dropdown-tail.svg
  src/assets/icons/header/white-search-icon.png
  src/css/sections/header.css
  src/css/sections/top-banner.css
  src/js/include/top-banner.js
  src/pages/includes/header.html
Labels: ✨feat

#47 feat: goods JS 완료
  src/assets/icons/quantity-btn__decrease-d.svg
  src/assets/icons/quantity-btn__decrease.svg
  src/assets/icons/quantity-btn__increase.svg
  src/assets/icons/view-all_icon-h.svg
  src/assets/icons/view-all_icon.svg
  src/css/sections/goods.css
  src/js/include/goods.js
  src/js/include/header.js
  src/js/main.js
  src/pages/includes/goods.html
  src/pages/includes/sidebar.html
Labels: ✨feat
